version: 2

project_name: demarkus-client

monorepo:
  tag_prefix: client/

builds:
  - id: demarkus
    main: ./cmd/demarkus
    binary: demarkus
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w

  - id: demarkus-tui
    main: ./cmd/demarkus-tui
    binary: demarkus-tui
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - "7"
    ignore:
      - goos: windows
        goarch: arm
    ldflags:
      - -s -w

archives:
  - id: demarkus
    builds:
      - demarkus
    name_template: "demarkus-client_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  - id: demarkus-tui
    builds:
      - demarkus-tui
    name_template: "demarkus-tui_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "demarkus-client_checksums.txt"

changelog:
  use: github-native
