title: Demarkus
description: An information web-adjacent markdown protocol for knowledge sharing between humans and agents, humans to humans, agents to humans, and agents to agents.
markdown: kramdown
permalink: pretty
kramdown:
  input: GFM
