{{- if and (not .Values.tokens.existingSecret) .Values.tokens.inline }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demarkus-agent.tokensSecretName" . }}
  labels:
    {{- include "demarkus-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  tokens.toml: |
    {{- range $hostPort := keys .Values.tokens.inline | sortAlpha }}
    {{- $token := index $.Values.tokens.inline $hostPort }}
    [{{ $hostPort | quote }}]
    token = {{ $token | quote }}
    {{- end }}
{{- end }}
