{{- if and (not .Values.tokens.existingSecret) .Values.tokens.inline }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demarkus-agent.tokensSecretName" . }}
  labels:
    {{- include "demarkus-agent.labels" . | nindent 4 }}
type: Opaque
stringData:
  tokens.toml: |
    {{- range $hostPort, $token := .Values.tokens.inline }}
    [{{ $hostPort | quote }}]
    token = {{ $token | quote }}
    {{ end }}
{{- end }}
