{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "demarkus-memory-broker.serviceAccountName" . }}
  labels:
    {{- include "demarkus-memory-broker.labels" . | nindent 4 }}
  {{- $ann := deepCopy (default dict .Values.serviceAccount.annotations) }}
  {{- if .Values.serviceAccount.workloadIdentity.gsa }}
  {{- $_ := set $ann "iam.gke.io/gcp-service-account" .Values.serviceAccount.workloadIdentity.gsa }}
  {{- end }}
  {{- if $ann }}
  annotations:
    {{- toYaml $ann | nindent 4 }}
  {{- end }}
{{- end }}
