{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "demarkus-knowledge-server.serviceAccountName" . }}
  labels:
    {{- include "demarkus-knowledge-server.labels" . | nindent 4 }}
  {{- $annotations := deepCopy (default dict .Values.serviceAccount.annotations) }}
  {{- $_ := set $annotations "iam.gke.io/gcp-service-account" .Values.serviceAccount.workloadIdentity.gsa }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
{{- end }}
