apiVersion: v1
kind: Service
metadata:
  name: {{ include "demarkus-knowledge-server.fullname" . }}
  labels:
    {{- include "demarkus-knowledge-server.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP | quote }}
  {{- end }}
  selector:
    {{- include "demarkus-knowledge-server.selectorLabels" . | nindent 4 }}
  ports:
    - name: mark
      protocol: UDP
      port: {{ .Values.server.udpPort }}
      targetPort: mark
