package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"
	"text/template"

	"gopkg.in/yaml.v3"
)

const generatedMarker = "<!-- Code generated by tools/plugin-prompts from plugins/prompt-source; DO NOT EDIT. -->"
const markdownlintDirective = "<!-- markdownlint-disable MD041 -->"

var canonicalOutputs = map[string]string{
	"memory/claude":      "plugins/claude-code",
	"memory/pi":          "plugins/pi-memory",
	"memory/opencode":    "plugins/opencode-memory",
	"knowledge/claude":   "plugins/claude-code-knowledge",
	"knowledge/pi":       "plugins/pi-knowledge",
	"knowledge/opencode": "plugins/opencode-knowledge",
	"memory/cursor":      "plugins/cursor-memory",
	"knowledge/cursor":   "plugins/cursor-knowledge",
}

type manifest struct {
	Targets []target `json:"targets"`
	Brands  []brand  `json:"brands"`
}

type target struct {
	Name             string `json:"name"`
	Surface          string `json:"surface"`
	Harness          string `json:"harness"`
	Agent            string `json:"agent"`
	Output           string `json:"output"`
	ProjectDir       string `json:"project_dir"`
	RepoInstructions string `json:"repo_instructions"`
	ToolForm         string `json:"tool_form"`
	// Plugin names surface in prose. PluginName is this target's own; the
	// sibling names let memory and knowledge prompts refer to each other.
	PluginName          string `json:"plugin_name"`
	MemoryPluginName    string `json:"memory_plugin_name"`
	KnowledgePluginName string `json:"knowledge_plugin_name"`
	// Store is the prose noun for the personal store ("soul" by default). It
	// is deliberately not "memory": hosts have a built-in memory feature and
	// agents conflated the two. Command and plugin names are unaffected.
	Store      string `json:"store_noun"`
	Stores     string `json:"store_noun_plural"`
	StoreTitle string `json:"-"`
}

const defaultStoreNoun = "soul"

// applyStoreDefaults fills the store noun triple; StoreTitle is derived.
func applyStoreDefaults(t *target) {
	if t.Store == "" {
		t.Store = defaultStoreNoun
	}
	if t.Stores == "" {
		t.Stores = t.Store + "s"
	}
	r := []rune(t.Store)
	t.StoreTitle = strings.ToUpper(string(r[0])) + string(r[1:])
}

type artifact struct {
	Path    string
	Content []byte
	Target  *target
	Copied  bool        // verbatim copy of a base plugin file, not a rendered template
	Mode    fs.FileMode // source mode for copies (hooks must stay executable); zero means 0o644
}

func main() {
	mode := "check"
	if len(os.Args) > 1 {
		mode = os.Args[1]
	}
	if mode != "check" && mode != "write" {
		fmt.Fprintln(os.Stderr, "usage: plugin-prompts [check|write]")
		os.Exit(2)
	}

	root, err := findRoot()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	artifacts, err := renderAll(root)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if mode == "write" {
		err = writeAll(root, artifacts)
	} else {
		err = checkAll(root, artifacts)
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Printf("plugin prompts %s: %d artifacts\n", mode, len(artifacts))
}

func findRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", fmt.Errorf("get working directory: %w", err)
	}
	for {
		manifestPath := filepath.Join(dir, "plugins", "prompt-source", "manifest.json")
		if _, statErr := os.Stat(manifestPath); statErr == nil {
			return dir, nil
		} else if !errors.Is(statErr, fs.ErrNotExist) {
			return "", fmt.Errorf("stat manifest %s: %w", manifestPath, statErr)
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", errors.New("plugins/prompt-source/manifest.json not found in this directory or its parents")
		}
		dir = parent
	}
}

func renderAll(root string) ([]artifact, error) {
	manifestPath := filepath.Join(root, "plugins", "prompt-source", "manifest.json")
	raw, err := os.ReadFile(manifestPath)
	if err != nil {
		return nil, fmt.Errorf("read manifest: %w", err)
	}
	spec, err := decodeManifest(raw)
	if err != nil {
		return nil, fmt.Errorf("parse manifest: %w", err)
	}
	if err := validateManifest(&spec); err != nil {
		return nil, err
	}
	if err := validateBrands(&spec); err != nil {
		return nil, err
	}

	var artifacts []artifact
	seen := map[string]string{}
	renderTargets := make([]*target, 0, len(spec.Targets)+len(spec.Brands))
	baseByName := map[string]*target{}
	for i := range spec.Targets {
		applyStoreDefaults(&spec.Targets[i])
		renderTargets = append(renderTargets, &spec.Targets[i])
		baseByName[spec.Targets[i].Name] = &spec.Targets[i]
	}
	for i := range spec.Brands {
		b := &spec.Brands[i]
		base := baseByName[b.Base]
		t := brandTarget(b, base)
		renderTargets = append(renderTargets, t)
		copied, err := brandArtifacts(root, b, base, t)
		if err != nil {
			return nil, err
		}
		for j := range copied {
			if err := claimOutput(seen, copied[j].Path, "brand "+b.Name); err != nil {
				return nil, err
			}
		}
		artifacts = append(artifacts, copied...)
	}
	for _, target := range renderTargets {
		if err := validateTarget(target); err != nil {
			return nil, err
		}
		templateRoot := filepath.Join(root, "plugins", "prompt-source", target.Surface)
		err := filepath.WalkDir(templateRoot, func(path string, entry fs.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if entry.IsDir() {
				return nil
			}
			isAlias := strings.HasSuffix(entry.Name(), ".md.alias")
			if !isAlias && !strings.HasSuffix(entry.Name(), ".tmpl") {
				return nil
			}
			rel, err := filepath.Rel(templateRoot, path)
			if err != nil {
				return err
			}
			var rendered []byte
			if isAlias {
				rendered, err = renderAlias(path, target)
			} else {
				rendered, err = renderTemplate(path, target)
			}
			if err != nil {
				return err
			}
			output := filepath.Join(root, target.Output, strings.TrimSuffix(strings.TrimSuffix(rel, ".tmpl"), ".alias"))
			if target.Harness == "cursor" && filepath.Base(filepath.Dir(output)) == "commands" {
				rendered, err = cursorCommand(strings.TrimSuffix(filepath.Base(output), ".md"), rendered)
				if err != nil {
					return fmt.Errorf("%s: %w", path, err)
				}
			}
			if err := claimOutput(seen, output, path); err != nil {
				return err
			}
			if err := validateArtifact(output, rendered, target); err != nil {
				return err
			}
			artifacts = append(artifacts, artifact{Path: output, Content: rendered, Target: target})
			return nil
		})
		if err != nil {
			return nil, fmt.Errorf("render %s: %w", target.Name, err)
		}
	}
	sort.Slice(artifacts, func(i, j int) bool { return artifacts[i].Path < artifacts[j].Path })
	return artifacts, nil
}

func decodeManifest(raw []byte) (manifest, error) {
	var spec manifest
	decoder := json.NewDecoder(bytes.NewReader(raw))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&spec); err != nil {
		return manifest{}, err
	}
	if err := decoder.Decode(&struct{}{}); !errors.Is(err, io.EOF) {
		if err == nil {
			return manifest{}, errors.New("unexpected trailing JSON value")
		}
		return manifest{}, err
	}
	return spec, nil
}

func validateManifest(spec *manifest) error {
	if len(spec.Targets) != len(canonicalOutputs) {
		return fmt.Errorf("manifest: got %d targets, want %d", len(spec.Targets), len(canonicalOutputs))
	}
	pairs := make(map[string]string, len(spec.Targets))
	outputs := make(map[string]string, len(spec.Targets))
	for i := range spec.Targets {
		target := &spec.Targets[i]
		if err := validateTarget(target); err != nil {
			return err
		}
		pair := target.Surface + "/" + target.Harness
		if previous, ok := pairs[pair]; ok {
			return fmt.Errorf("manifest targets %s and %s duplicate surface/harness %s", previous, target.Name, pair)
		}
		pairs[pair] = target.Name
		if previous, ok := outputs[target.Output]; ok {
			return fmt.Errorf("manifest targets %s and %s duplicate output %s", previous, target.Name, target.Output)
		}
		outputs[target.Output] = target.Name
		if filepath.IsAbs(target.Output) || hasParentTraversal(target.Output) {
			return fmt.Errorf("manifest target %s: output must be a repository-relative path without parent traversal", target.Name)
		}
		if want := canonicalOutputs[pair]; target.Output != want {
			return fmt.Errorf("manifest target %s: output %q, want %q", target.Name, target.Output, want)
		}
	}
	return nil
}

func hasParentTraversal(path string) bool {
	parts := strings.FieldsFunc(path, func(r rune) bool { return r == '/' || r == '\\' })
	return slices.Contains(parts, "..")
}

func validateTarget(target *target) error {
	if target.Name == "" || target.Output == "" || target.Agent == "" || target.ProjectDir == "" || target.RepoInstructions == "" || target.ToolForm == "" {
		return fmt.Errorf("manifest target %q: name, output, agent, project_dir, repo_instructions, and tool_form are required", target.Name)
	}
	if target.Surface != "memory" && target.Surface != "knowledge" {
		return fmt.Errorf("manifest target %s: invalid surface %q", target.Name, target.Surface)
	}
	if target.MemoryPluginName == "" {
		target.MemoryPluginName = "demarkus-memory"
	}
	if target.KnowledgePluginName == "" {
		target.KnowledgePluginName = "demarkus-knowledge"
	}
	if target.PluginName == "" {
		target.PluginName = target.MemoryPluginName
		if target.Surface == "knowledge" {
			target.PluginName = target.KnowledgePluginName
		}
	}
	if target.Harness != "claude" && target.Harness != "pi" && target.Harness != "opencode" && target.Harness != "cursor" {
		return fmt.Errorf("manifest target %s: invalid harness %q", target.Name, target.Harness)
	}
	return nil
}

func renderTemplate(path string, target *target) ([]byte, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	tmpl, err := template.New(filepath.Base(path)).Option("missingkey=error").Parse(string(raw))
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", path, err)
	}
	var output bytes.Buffer
	if err := tmpl.Execute(&output, target); err != nil {
		return nil, fmt.Errorf("execute %s for %s: %w", path, target.Name, err)
	}
	// addMarker prepends comments, so an unclosed block would no longer look like
	// frontmatter downstream and escape validateFrontmatter.
	if text := output.String(); strings.HasPrefix(text, "---\n") {
		if _, ok := frontmatterEnd(text); !ok {
			return nil, fmt.Errorf("%s: frontmatter block is not closed", path)
		}
	}
	return addMarker(output.Bytes()), nil
}

// claimOutput rejects two sources (e.g. foo.md.tmpl and foo.md.alias) mapping
// to one generated path, which writeAll would otherwise silently overwrite.
func claimOutput(seen map[string]string, output, source string) error {
	key := filepath.Clean(output)
	if prev, ok := seen[key]; ok {
		return fmt.Errorf("%s: output %s already generated from %s", source, output, prev)
	}
	seen[key] = source
	return nil
}

// renderAlias renders a deprecated command alias: a `<old>.md.alias` file in
// commands/ names the target command, and the alias ships the target's full
// body under the old name so both names behave identically on every harness.
func renderAlias(path string, target *target) ([]byte, error) {
	if !strings.HasSuffix(path, ".md.alias") {
		return nil, fmt.Errorf("%s: alias files must be named <command>.md.alias", path)
	}
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	name := strings.TrimSpace(string(raw))
	if name == "" || strings.ContainsAny(name, "/\\ \n") {
		return nil, fmt.Errorf("%s: alias must name one command", path)
	}
	if filepath.Base(filepath.Dir(path)) != "commands" {
		return nil, fmt.Errorf("%s: aliases are only supported under commands/", path)
	}
	if strings.TrimSuffix(filepath.Base(path), ".md.alias") == name {
		return nil, fmt.Errorf("%s: alias targets itself", path)
	}
	rendered, err := renderTemplate(filepath.Join(filepath.Dir(path), name+".md.tmpl"), target)
	if err != nil {
		return nil, fmt.Errorf("%s: alias target: %w", path, err)
	}
	text := string(rendered)
	end, ok := frontmatterEnd(text)
	if !ok {
		return nil, fmt.Errorf("%s: alias target has no frontmatter", path)
	}
	head, body := text[:end], text[end:]
	marker := "\ndescription: "
	at := strings.Index(head, marker)
	if at < 0 {
		return nil, fmt.Errorf("%s: alias target has no description", path)
	}
	at += len(marker)
	if at < len(head) && head[at] == '"' {
		at++ // quoted description: stay inside the quotes
	}
	return []byte(head[:at] + "Deprecated alias of /" + name + ". " + head[at:] + body), nil
}

// cursorCommand reshapes a command's frontmatter for Cursor: `name` comes from
// the file name and `argument-hint` (a Claude Code key) is dropped, since Cursor
// documents only name and description.
func cursorCommand(name string, content []byte) ([]byte, error) {
	text := string(content)
	end, ok := frontmatterEnd(text)
	if !ok {
		return nil, errors.New("cursor command has no frontmatter")
	}
	var head []string
	for line := range strings.SplitSeq(strings.TrimSuffix(text[4:end-4], "\n"), "\n") {
		if strings.HasPrefix(line, "argument-hint:") || strings.HasPrefix(line, "name:") {
			continue
		}
		head = append(head, line)
	}
	return []byte("---\nname: " + name + "\n" + strings.Join(head, "\n") + "\n---\n" + text[end:]), nil
}

// frontmatterEnd returns the offset just past a leading `---` block.
func frontmatterEnd(text string) (int, bool) {
	if !strings.HasPrefix(text, "---\n") {
		return 0, false
	}
	end := strings.Index(text[4:], "\n---\n")
	if end < 0 {
		return 0, false
	}
	return end + 9, true
}

// validateFrontmatter parses a leading `---` block as strict YAML. Hosts use
// strict parsers (Cursor ships js-yaml), so an unquoted description containing
// ": " silently drops the command or skill from the menu.
func validateFrontmatter(text string) error {
	end, ok := frontmatterEnd(text)
	if !ok {
		return nil
	}
	var fields map[string]any
	if err := yaml.Unmarshal([]byte(text[4:end-4]), &fields); err != nil {
		return fmt.Errorf("frontmatter is not valid YAML: %w", err)
	}
	if d, ok := fields["description"]; ok {
		if _, isString := d.(string); !isString {
			return fmt.Errorf("frontmatter description must be a string, got %T", d)
		}
	}
	return nil
}

func addMarker(content []byte) []byte {
	text := strings.TrimRight(string(content), "\n") + "\n"
	if at, ok := frontmatterEnd(text); ok {
		return []byte(text[:at] + markdownlintDirective + "\n" + generatedMarker + "\n" + text[at:])
	}
	return []byte(markdownlintDirective + "\n" + generatedMarker + "\n" + text)
}

func validateArtifact(path string, content []byte, target *target) error {
	text := string(content)
	if strings.Contains(text, "{{") || strings.Contains(text, "}}") {
		return fmt.Errorf("%s: unresolved template token", path)
	}
	if strings.HasSuffix(path, "SKILL.md") {
		if !strings.HasPrefix(text, "---\n") || !strings.Contains(text, "\nname:") || !strings.Contains(text, "\ndescription:") {
			return fmt.Errorf("%s: invalid skill frontmatter", path)
		}
	}
	if err := validateFrontmatter(text); err != nil {
		return fmt.Errorf("%s: %w", path, err)
	}
	for _, forbidden := range forbiddenTerms(target.Harness) {
		if strings.Contains(text, forbidden) {
			return fmt.Errorf("%s: foreign harness term %q", path, forbidden)
		}
	}
	if strings.HasSuffix(path, filepath.Join("context", "session-guidance.md")) {
		h1 := 0
		for line := range strings.SplitSeq(text, "\n") {
			if strings.HasPrefix(line, "# ") {
				h1++
			}
		}
		want := 1
		if target.Surface == "knowledge" {
			want = 0
		}
		if h1 != want {
			return fmt.Errorf("%s: got %d static H1 headings, want %d", path, h1, want)
		}
	}
	return nil
}

func forbiddenTerms(harness string) []string {
	common := []string{"OpenClaw", "openclaw", "mcporter"}
	switch harness {
	case "claude":
		return append(common, "OpenCode", "opencode", "pi-mcp-adapter", "AGENTS.md")
	case "pi":
		return append(common, "OpenCode", "opencode", "CLAUDE_PROJECT_DIR", "AskUserQuestion", "mcp__", "Claude Code")
	case "cursor":
		return append(common, "OpenCode", "opencode", "CLAUDE_PROJECT_DIR", "AskUserQuestion", "mcp__", "Claude Code", "pi-mcp-adapter")
	default:
		return append(common, "Claude Code", "CLAUDE_PROJECT_DIR", "AskUserQuestion", "pi-mcp-adapter", "mcp__")
	}
}

func writeAll(root string, artifacts []artifact) error {
	expected := make(map[string]struct{}, len(artifacts))
	for i := range artifacts {
		artifact := &artifacts[i]
		expected[filepath.Clean(artifact.Path)] = struct{}{}
		if err := os.MkdirAll(filepath.Dir(artifact.Path), 0o755); err != nil {
			return fmt.Errorf("create output directory: %w", err)
		}
		mode := artifact.Mode
		if mode == 0 {
			mode = 0o644
		}
		if err := os.WriteFile(artifact.Path, artifact.Content, mode); err != nil {
			return fmt.Errorf("write %s: %w", artifact.Path, err)
		}
		// WriteFile keeps an existing file's mode; make the copy's mode win.
		if err := os.Chmod(artifact.Path, mode); err != nil {
			return fmt.Errorf("chmod %s: %w", artifact.Path, err)
		}
	}
	return pruneBrandOutputs(root, artifacts, expected)
}

// pruneBrandOutputs deletes files under brand outputs that no artifact
// produced, so write converges on the check that reports them as stale.
// Canonical plugins are never pruned: they mix generated and hand-kept files.
func pruneBrandOutputs(root string, artifacts []artifact, expected map[string]struct{}) error {
	for _, output := range brandOutputs(artifacts) {
		dir := filepath.Join(root, output)
		var stale []string
		err := filepath.WalkDir(dir, func(path string, entry fs.DirEntry, walkErr error) error {
			if walkErr != nil {
				return walkErr
			}
			if _, ok := expected[filepath.Clean(path)]; !entry.IsDir() && !ok {
				stale = append(stale, path)
			}
			return nil
		})
		if err != nil {
			return fmt.Errorf("scan brand output %s: %w", dir, err)
		}
		for _, path := range stale {
			if err := os.Remove(path); err != nil {
				return fmt.Errorf("remove stale %s: %w", path, err)
			}
			fmt.Printf("removed stale brand file %s\n", filepath.ToSlash(strings.TrimPrefix(path, root+string(filepath.Separator))))
		}
	}
	return nil
}

// brandOutputs lists the distinct brand output dirs among the artifacts.
func brandOutputs(artifacts []artifact) []string {
	seen := map[string]struct{}{}
	var outputs []string
	for i := range artifacts {
		output := artifacts[i].Target.Output
		if _, ok := seen[output]; ok || !strings.HasPrefix(filepath.ToSlash(output), brandOutputPrefix) {
			continue
		}
		seen[output] = struct{}{}
		outputs = append(outputs, output)
	}
	sort.Strings(outputs)
	return outputs
}

func checkAll(root string, artifacts []artifact) error {
	var drift []string
	expected := make(map[string]struct{}, len(artifacts))
	for i := range artifacts {
		artifact := &artifacts[i]
		expected[filepath.Clean(artifact.Path)] = struct{}{}
		actual, err := os.ReadFile(artifact.Path)
		if err != nil {
			if !errors.Is(err, fs.ErrNotExist) {
				return fmt.Errorf("read generated artifact %s: %w", artifact.Path, err)
			}
			drift = append(drift, filepath.ToSlash(strings.TrimPrefix(artifact.Path, root+string(filepath.Separator))))
			continue
		}
		if !bytes.Equal(actual, artifact.Content) {
			drift = append(drift, filepath.ToSlash(strings.TrimPrefix(artifact.Path, root+string(filepath.Separator))))
		}
	}
	outputs := make(map[string]struct{})
	for i := range artifacts {
		outputs[artifacts[i].Target.Output] = struct{}{}
	}
	for output := range outputs {
		// A brand directory is generated in full, so every file in it is
		// managed; canonical plugins mix generated prompts with hand-kept files.
		subtrees := []string{"commands", "context", "skills"}
		managedOnly := false
		if strings.HasPrefix(filepath.ToSlash(output), brandOutputPrefix) {
			subtrees = []string{""}
			managedOnly = true
		}
		for _, subtree := range subtrees {
			dir := filepath.Join(root, output, subtree)
			err := filepath.WalkDir(dir, func(path string, entry fs.DirEntry, walkErr error) error {
				if walkErr != nil {
					return walkErr
				}
				if entry.IsDir() || (!managedOnly && filepath.Ext(path) != ".md") {
					return nil
				}
				if _, ok := expected[filepath.Clean(path)]; !ok {
					drift = append(drift, filepath.ToSlash(strings.TrimPrefix(path, root+string(filepath.Separator)))+" (unexpected)")
				}
				return nil
			})
			if err != nil {
				return fmt.Errorf("scan generated output %s: %w", dir, err)
			}
		}
	}
	if len(drift) > 0 {
		sort.Strings(drift)
		return fmt.Errorf("generated plugin prompts are stale:\n  %s\nrun: cd tools && go run ./plugin-prompts write", strings.Join(compact(drift), "\n  "))
	}
	return nil
}

func compact(values []string) []string {
	if len(values) == 0 {
		return nil
	}
	result := []string{values[0]}
	for _, value := range values[1:] {
		if value != result[len(result)-1] {
			result = append(result, value)
		}
	}
	return result
}
