import assert from "node:assert/strict";
import { dirname, join } from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import { loadCommand } from "../src/demarkus-memory.ts";

const commands = join(dirname(fileURLToPath(import.meta.url)), "..", "commands");

test("loadCommand reads a generated command and preserves argument substitution", () => {
  const command = loadCommand("promote.md", commands);

  assert.match(command.description, /^Promote a soul document/);
  assert.match(command.template, /Code generated by tools\/plugin-prompts/);
  assert.match(command.template, /\$ARGUMENTS/);
  assert.match(command.template, /User arguments \(may be empty\): \$ARGUMENTS\n$/);
});
